version: '3.8'

services:
  snippets:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
  snippets-db:
    image: postgres:13-alpine
    volumes:
      # to persist the data beyond the life of the container
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=snippets
      - POSTGRES_PASSWORD=snippets
      - POSTGRES_DB=snippets_dev

volumes:
  postgres_data: